Neos:
  Neos:
    Ui:
      frontendConfiguration:
        "Visol.Neos.ClipboardInputTransformation":
          replacements:
          # for example replace LSEP and PSEP unicode chars
          #  - search: "\u2029"
          #    replace: ""
          #  - search: "\u2028"
          #    replace: ""
