Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Visol.Neos.ClipboardInputTransformation':
            resource: resource://Visol.Neos.ClipboardInputTransformation/Public/NeosUserInterface/Plugin.js
